### PR TITLE
Homebutton

### PR DESCRIPTION
**Pull request by LeybaAir**
fixed home button to show

### CODE REVIEW

**Review by Donnie46 — DISMISSED** [review]
Works fine

**Review by Donnie46 — APPROVED** [review]
Works good

**Review by Donnie46 — CHANGES_REQUESTED** [review]
Works good

**Review by Donnie46 — APPROVED** [review]
Good

**Review by Donnie46 — DISMISSED** [review]
Good

**Review by Jflatley487 — DISMISSED** [review]

**Review by SKJauch — DISMISSED** [review]
good

**Review by Donnie46 — DISMISSED** [review]

**Pull request closed without merging**
